### ISSUE TITLE
Continue export on ValueError instead of exiting

### ISSUE THREAD

**Issue by ecommandeur** [ecommandeur/python-xlsx-conv#10]
At present xlsx-conv will exit when it encounters a Value Error such as a Date formatted field that contains a date value that is out of range.

It would be nicer if the tool gives information on the value error (if possible metadata such as which cell caused it) and then continues, leaving the value blank. 

```
xlsx-conv: error: Failed to convert sheet
year 112873435 is out of range
Traceback (most recent call last):
  File "xlsx-conv.py", line 137, in <module>
  File "xlsx-conv.py", line 104, in convertSheet
  File "site-packages\openpyxl\cell\read_only.py", line 117, in value
  File "site-packages\openpyxl\utils\datetime.py", line 97, in from_excel
ValueError: year 112873435 is out of range
```

**Comment by ecommandeur** [comment]
This bug actually occurred on an Excel using an older version of xlsx-conv. Is this still relevant?

**Comment by ecommandeur** [comment]
At least we should write which cell was the offender (row and column nr) if there was any Exception at all.

**Comment by ecommandeur** [comment]
Ok, it seems this was a bug https://bitbucket.org/openpyxl/openpyxl/issues/1152/year-is-out-of-range-error

**Comment by ecommandeur** [comment]
This happens in load_workbook, so we are dependent on the error details load_workbook gives back. This issue can be closed.
